In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.style as style
from tqdm import tqdm 
tqdm.pandas()
plt.rcParams.update({'axes.labelsize':16})
plt.rcParams.update({'axes.titlesize':16})
plt.rcParams.update({'legend.fontsize':16})
plt.rcParams['xtick.labelsize'] = 16
plt.rcParams['ytick.labelsize'] = 16
plt.rcParams['lines.linewidth'] = 4
style.use('ggplot')
import os
os.chdir('../')
from python_code import simple_gibbs, gp_gibbs
os.chdir('notebooks')
from sklearn.decomposition import PCA

<class 'python_code.simple_gibbs.GibbsSampler'>


In [5]:
np.array([1,2,3,4]) * np.eye(4)

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [23]:
eyes = np.tile(np.eye(4)[:, :, None], 10)

In [30]:
ni = np.array([5,4,5])

In [39]:
sigs = np.linspace(1,100,5)

In [40]:
(eyes*sigs)[:,:,2]

ValueError: operands could not be broadcast together with shapes (4,4,10) (5,) 

In [42]:
[sigs[n] * np.eye(val) for n, val in enumerate(ni)]

[array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]),
 array([[25.75,  0.  ,  0.  ,  0.  ],
        [ 0.  , 25.75,  0.  ,  0.  ],
        [ 0.  ,  0.  , 25.75,  0.  ],
        [ 0.  ,  0.  ,  0.  , 25.75]]),
 array([[50.5,  0. ,  0. ,  0. ,  0. ],
        [ 0. , 50.5,  0. ,  0. ,  0. ],
        [ 0. ,  0. , 50.5,  0. ,  0. ],
        [ 0. ,  0. ,  0. , 50.5,  0. ],
        [ 0. ,  0. ,  0. ,  0. , 50.5]])]